# Generated by Django 4.2 on 2024-12-27 21:08

from django.db import migrations


def init_data(apps, label):
    CoverdCallDynamicConfig = apps.get_model("coverd_call", "CoverdCallDynamicConfig")
    CoverdCallDynamicConfig.objects.create(
        token="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwOTEyODE4ODU5MSIsImV4cGlyZV9hdCI6IjIyLzAxLzI1In0.gKT9qnYAZmeI65lhm2mtw4j0QXqP2-mzaLcovQqfv4Y"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("option", "0001_initial"),
    ]

    operations = [migrations.RunPython(init_data, migrations.RunPython.noop)]
