# Generated by Django 4.2 on 2024-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverdCallDynamicConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.FloatField(default=0.9)),
                ("minimum_profit", models.FloatField(default=40)),
                ("token", models.CharField(default="Bearer test", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CoverdCallOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_price_diff_percent_by_final_price", models.FloatField()),
                (
                    "cover_call_final_price_diff_percent_by_base_price",
                    models.FloatField(),
                ),
                ("symbol", models.CharField(max_length=30)),
                ("original_symbol", models.CharField(max_length=30)),
                ("end_date", models.DateField()),
                ("delta", models.FloatField()),
                ("highest_bid_price", models.IntegerField()),
                ("lowest_ask_price", models.IntegerField()),
                ("highest_bid_value", models.IntegerField()),
                ("guarantee", models.IntegerField()),
                ("original_symbol_lowest_ask_price", models.IntegerField()),
                ("cover_call_final_price", models.IntegerField()),
                ("cover_call_volume", models.IntegerField()),
                ("cover_call", models.IntegerField()),
                ("cover_call_profit", models.FloatField()),
                ("cover_call_in_end_date", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_date_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="coverdcalloptions",
            constraint=models.UniqueConstraint(
                fields=("created_date_at", "symbol"), name="nemidunam"
            ),
        ),
    ]
